version: "3"
services: 
    app:
        container_name: ticket_system
        restart: always
        build: .
        ports: 
            - '80:3000'
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
    worker:
        container_name: email_worker
        restart: always
        build: .
        ports: 
            - '8080:8080'
        links: 
            - mongo